"use client";
import {FormEvent,useEffect,useState} from "react";
import {useParams} from "next/navigation";
import AppShell from "@/components/AppShell";
import ContractTabs from "@/components/ContractTabs";
import Modal from "@/components/Modal";
import {dateBR,insertRow,listRows,money,updateRow,deleteRow} from "@/lib/supabase-data";

export default function Detail(){
  const {id}=useParams<{id:string}>();const [c,setC]=useState<any>(null),[adds,setAdds]=useState<any[]>([]),[events,setEvents]=useState<any[]>([]),[edit,setEdit]=useState(false),[eventOpen,setEventOpen]=useState(false),[error,setError]=useState("");
  const load=async()=>{try{const cs=await listRows("contracts",{id});setC(cs[0]);setAdds(await listRows("addenda",{contract_id:id}));setEvents(await listRows("contract_events",{contract_id:id}))}catch(e:any){setError(e.message)}};
  useEffect(()=>{load()},[id]);
  if(!c)return <AppShell><div className="card">Carregando...</div></AppShell>;
  const av=adds.filter(x=>["Aprovado","Formalizado"].includes(x.status)).reduce((a,x)=>a+Number(x.value||0),0);const total=Number(c.contract_value||0)+av;const progress=total?Math.min(100,Number(c.measured_value||0)/total*100):0;
  async function saveContract(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await updateRow("contracts",id,{client_name:String(f.get("client_name")||""),object:String(f.get("object")||""),contract_value:Number(f.get("contract_value")||0),status:String(f.get("status")||""),notice_number:String(f.get("notice_number")||""),modality:String(f.get("modality")||""),process_number:String(f.get("process_number")||""),location:String(f.get("location")||""),manager_name:String(f.get("manager_name")||""),manager_email:String(f.get("manager_email")||""),manager_phone:String(f.get("manager_phone")||""),start_date:String(f.get("start_date")||"")||null,end_date:String(f.get("end_date")||"")||null,term_end_date:String(f.get("term_end_date")||"")||null,execution_days:Number(f.get("execution_days")||0)||null,notes:String(f.get("notes")||"")});setEdit(false);await load()}
  async function saveEvent(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await insertRow("contract_events",{contract_id:id,event_date:String(f.get("event_date")||new Date().toISOString().slice(0,10)),event_type:String(f.get("event_type")||"Registro"),title:String(f.get("title")||""),description:String(f.get("description")||""),responsible:String(f.get("responsible")||"")});setEventOpen(false);await load()}
  return <AppShell>{error&&<div className="warning">{error}</div>}<div className="topbar"><div><h1 className="section-title">Contrato {c.contract_number}</h1><div className="muted">{c.object}</div></div><div className="actions"><span className="badge">{c.status}</span><button className="btn secondary" onClick={()=>setEdit(true)}>Editar contrato</button></div></div>
    <ContractTabs id={id}/><div className="summary"><div className="card"><div className="muted">Original</div><div className="value">{money(c.contract_value)}</div></div><div className="card"><div className="muted">Com aditivos</div><div className="value">{money(total)}</div></div><div className="card"><div className="muted">Medido</div><div className="value">{money(c.measured_value)}</div></div><div className="card"><div className="muted">Recebido</div><div className="value">{money(c.received_value)}</div></div><div className="card"><div className="muted">Pendente</div><div className="value">{money(Math.max(0,Number(c.measured_value)-Number(c.received_value)))}</div></div></div>
    <div className="grid two dashboard-panels"><section className="card"><h3>Dados contratuais</h3><div className="details-grid"><div><span>Órgão</span><strong>{c.client_name||"—"}</strong></div><div><span>Edital</span><strong>{c.notice_number||"—"}</strong></div><div><span>Modalidade</span><strong>{c.modality||"—"}</strong></div><div><span>Processo</span><strong>{c.process_number||"—"}</strong></div><div><span>Local</span><strong>{c.location||"—"}</strong></div><div><span>Fiscal</span><strong>{c.manager_name||"—"}</strong></div><div><span>Execução</span><strong>{dateBR(c.start_date)} a {dateBR(c.end_date)}</strong></div><div><span>Vigência</span><strong>{dateBR(c.term_end_date)}</strong></div></div></section><section className="card"><h3>Avanço financeiro</h3><div className="large-progress"><span style={{width:`${progress}%`}}/></div><div className="progress-label"><strong>{progress.toFixed(1)}%</strong><span>{money(c.measured_value)} de {money(total)}</span></div><p className="muted">{c.notes||"Nenhuma observação cadastrada."}</p></section></div>
    <div className="topbar compact"><div><h2>Linha do tempo</h2><div className="muted">Ocorrências, comunicações e marcos do contrato</div></div><button className="btn" onClick={()=>setEventOpen(true)}>Novo evento</button></div>
    <section className="contract-timeline">{events.map(e=><div className="event-card" key={e.id}><div className="event-date">{dateBR(e.event_date)}</div><div><span className="badge">{e.event_type}</span><h3>{e.title}</h3><p>{e.description||"Sem descrição."}</p><small>{e.responsible||"Sem responsável"}</small></div><button className="btn danger" onClick={async()=>{await deleteRow("contract_events",e.id);await load()}}>Excluir</button></div>)}{!events.length&&<div className="card empty">Nenhum evento cadastrado.</div>}</section>
    <Modal open={edit} title="Editar contrato" onClose={()=>setEdit(false)}><form className="form-grid" onSubmit={saveContract}><div className="field"><label>Órgão</label><input className="input" name="client_name" defaultValue={c.client_name}/></div><div className="field"><label>Valor</label><input className="input" type="number" step="0.01" name="contract_value" defaultValue={c.contract_value}/></div><div className="field full"><label>Objeto</label><input className="input" name="object" defaultValue={c.object}/></div><div className="field"><label>Edital</label><input className="input" name="notice_number" defaultValue={c.notice_number}/></div><div className="field"><label>Modalidade</label><input className="input" name="modality" defaultValue={c.modality}/></div><div className="field"><label>Processo</label><input className="input" name="process_number" defaultValue={c.process_number}/></div><div className="field"><label>Local</label><input className="input" name="location" defaultValue={c.location}/></div><div className="field"><label>Fiscal</label><input className="input" name="manager_name" defaultValue={c.manager_name}/></div><div className="field"><label>E-mail do fiscal</label><input className="input" name="manager_email" defaultValue={c.manager_email}/></div><div className="field"><label>Telefone do fiscal</label><input className="input" name="manager_phone" defaultValue={c.manager_phone}/></div><div className="field"><label>Início</label><input className="input" type="date" name="start_date" defaultValue={c.start_date?.slice(0,10)}/></div><div className="field"><label>Término</label><input className="input" type="date" name="end_date" defaultValue={c.end_date?.slice(0,10)}/></div><div className="field"><label>Fim da vigência</label><input className="input" type="date" name="term_end_date" defaultValue={c.term_end_date?.slice(0,10)}/></div><div className="field"><label>Prazo (dias)</label><input className="input" type="number" name="execution_days" defaultValue={c.execution_days}/></div><div className="field"><label>Status</label><select className="input" name="status" defaultValue={c.status}><option>Planejamento</option><option>Em execução</option><option>Paralisado</option><option>Concluído</option><option>Rescindido</option></select></div><div className="field full"><label>Observações</label><textarea className="input" name="notes" defaultValue={c.notes}/></div><div className="full actions"><button className="btn">Salvar alterações</button></div></form></Modal>
    <Modal open={eventOpen} title="Novo evento" onClose={()=>setEventOpen(false)}><form className="form-grid" onSubmit={saveEvent}><div className="field"><label>Data</label><input className="input" type="date" name="event_date" defaultValue={new Date().toISOString().slice(0,10)}/></div><div className="field"><label>Tipo</label><select className="input" name="event_type"><option>Registro</option><option>Ordem de serviço</option><option>Aditivo</option><option>Medição</option><option>Notificação</option><option>Paralisação</option><option>Reunião</option><option>Pagamento</option></select></div><div className="field full"><label>Título</label><input className="input" name="title" required/></div><div className="field full"><label>Descrição</label><textarea className="input" name="description"/></div><div className="field full"><label>Responsável</label><input className="input" name="responsible"/></div><div className="full actions"><button className="btn">Salvar evento</button></div></form></Modal>
  </AppShell>
}
